[package]
name = "setmint-engine"
version = "0.9.0"
authors = ["Setheum Labs"]
edition = "2018"

[dependencies]
# external dependencies
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }

# Substrate dependencies
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8" }
sp-application-crypto = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8" }
sp-io = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8" }

# orml dependencies
orml-tokens = { path = "../../../lib-openrml/tokens", default-features = false }
orml-traits = { path = "../../../lib-openrml/traits", default-features = false }
orml-utilities = { path = "../../../lib-openrml/utilities", default-features = false }

# local dependencies
support = { package = "setheum-support", path = "../../support", default-features = false }
setmint = { package = "setmint-manager", path = "../setmint-manager", default-features = false }
primitives = { package = "setheum-primitives", path = "../../../primitives", default-features = false }

[dev-dependencies]
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8" }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8" }
orml-currencies = { path = "../../../lib-openrml/currencies" }
setheum-dex = { path = "../../dex/dex" }
serp-treasury = { package = "serp-treasury", path = "../../serp/serp-treasury" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"orml-tokens/std",
	"orml-traits/std",
	"sp-application-crypto/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"support/std",
	"setmint/std",
	"primitives/std",
	"orml-utilities/std",
]
try-runtime = ["frame-support/try-runtime"]
