[package]
name = "newrome-runtime"
version = "0.8.0"
authors = ["Setheum Labs"]
edition = "2018"
build = "build.rs"

[dependencies]
# external dependencies
smallvec = "1.4.0"
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
hex-literal = { version = "0.3.1" }
libsecp256k1 = { version = "0.3.4", default-features = false, optional = true }
# Substrate dependencies
frame-benchmarking = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4", optional = true }
frame-executive = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
frame-system-rpc-runtime-api = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
frame-try-runtime = { default-features = false, optional = true, version = '0.9.0', git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
pallet-authorship = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
pallet-babe = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
pallet-balances = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
pallet-bounties = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
pallet-collective = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
pallet-grandpa = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
pallet-indices = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
pallet-membership = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
pallet-multisig = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
pallet-offences = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
pallet-proxy = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
pallet-randomness-collective-flip = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
pallet-recovery = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
pallet-scheduler = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
pallet-session = { version = "3.0.0", features = ["historical"], default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
pallet-sudo = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
pallet-timestamp = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
pallet-tips = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
pallet-transaction-payment-rpc-runtime-api = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
pallet-treasury = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
pallet-utility = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-api = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-application-crypto = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-block-builder = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-consensus-babe = { version = "0.9.0", default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-inherents = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-io = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-offchain = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-session = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-staking = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-transaction-pool = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-version = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }

# orml dependencies
orml-auction = { path = "../../lib-openrml/auction", default-features = false }
orml-authority = { path = "../../lib-openrml/authority", default-features = false }
orml-benchmarking = { path = "../../lib-openrml/benchmarking", default-features = false, optional = true }
orml-oracle = { path = "../../lib-openrml/oracle", default-features = false }
orml-oracle-rpc-runtime-api = { path = "../../lib-openrml/oracle/rpc/runtime-api", default-features = false }
orml-tokens = { path = "../../lib-openrml/tokens", default-features = false }
orml-traits = { path = "../../lib-openrml/traits", default-features = false }
orml-vesting = { path = "../../lib-openrml/vesting", default-features = false }
orml-rewards = { path = "../../lib-openrml/rewards", default-features = false }
orml-nft= { path = "../../lib-openrml/nft", default-features = false }

# local dependencies
# - bridges
setheum-chainbridge = { path = "../../lib-serml/bridges/chainbridge", default-features = false }
setheum-renvm-bridge = { path = "../../lib-serml/bridges/renvm-bridge", default-features = false }
# - dex
setheum-dex = { path = "../../lib-serml/dex/dex", default-features = false }
setheum-incentives = { path = "../../lib-serml/dex/incentives", default-features = false }
# - evm
setheum-evm = { path = "../../lib-serml/evm/evm", default-features = false }
setheum-evm-accounts = { path = "../../lib-serml/evm/evm-accounts", default-features = false }
setheum-evm-bridge = { path = "../../lib-serml/evm/evm-bridge", default-features = false }
setheum-evm-manager = { path = "../../lib-serml/evm/evm-manager", default-features = false }
setheum-evm-rpc-runtime-api = { path = "../../lib-serml/evm/evm/rpc/runtime_api",  default-features = false }
# - prices
setheum-prices = { path = "../../lib-serml/prices", default-features = false }
# - serp
serp-auction = { path = "../../lib-serml/serp/serp-auction", default-features = false }
serp-treasury = { path = "../../lib-serml/serp/serp-treasury", default-features = false }
serp-staking = { default-features = false, path = "../../lib-serml/serp/serp-staking" }
serp-staking-reward-curve = { default-features = false, path = "../../lib-serml/serp/serp-staking/reward-curve" }
# - settmint
settmint-engine = { path = "../../lib-serml/settmint/settmint-engine", default-features = false }
settmint-gateway = { path = "../../lib-serml/settmint/settmint-gateway", default-features = false }
settmint-manager = { path = "../../lib-serml/settmint/settmint-manager", default-features = false }
# - support
setheum-support = { path = "../../lib-serml/support", default-features = false }
# - tokens
setheum-currencies = { path = "../../lib-serml/tokens/currencies", default-features = false }
setheum-nft = { path = "../../lib-serml/tokens/nft", default-features = false }
# - transaction-payment
setheum-transaction-payment = { path = "../../lib-serml/transaction-payment", default-features = false }
# - primitives
primitives = { package = "setheum-primitives", path = "../../primitives", default-features = false }
# - runtime
runtime-common = { path = "../common", default-features = false }

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }

[dev-dependencies]
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }

[features]
default = ["std"]
no_std = []
std = [
	"codec/std",
	"serde",

	"frame-benchmarking/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"frame-try-runtime/std",
	"pallet-babe/std",
	"pallet-balances/std",
	"pallet-bounties/std",
	"pallet-collective/std",
	"pallet-grandpa/std",
	"pallet-indices/std",
	"pallet-membership/std",
	"pallet-multisig/std",
	"pallet-proxy/std",
	"pallet-randomness-collective-flip/std",
	"pallet-recovery/std",
	"pallet-scheduler/std",
	"pallet-session/std",
	"serp-staking/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-tips/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-treasury/std",
	"pallet-utility/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-babe/std",
	"sp-core/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",

	"orml-auction/std",
	"orml-authority/std",
	"orml-benchmarking/std",
	"orml-oracle-rpc-runtime-api/std",
	"orml-oracle/std",
	"orml-tokens/std",
	"orml-traits/std",
	"orml-vesting/std",
	"orml-rewards/std",
	"orml-nft/std",

	"setheum-renvm-bridge/std
	"setheum-dex/std",
	"setheum-incentives/std",
	"setheum-evm/std",
	"setheum-evm-accounts/std",
	"setheum-evm-bridge/std",
	"setheum-evm-manager/std",
	"setheum-prices/std",
	"serp-auction/std",
	"serp-treasury/std",
	"settmint-engine/std",
	"settmint-gateway/std",
	"settmint-manager/std",
	"setheum-support/std",
	"setheum-currencies/std",
	"setheum-nft/std",
	"setheum-transaction-payment/std",
	"primitives/std",
	"runtime-common/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"orml-benchmarking",
	"libsecp256k1/hmac",

	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-collective/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"orml-authority/runtime-benchmarks",
	"orml-vesting/runtime-benchmarks",
	"orml-tokens/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",

	"setheum-chainbridge/runtime-benchmarks",
	"setheum-nft/runtime-benchmarks",

	"sp-api/disable-logging",
]
# When enabled, the runtime api will not be build.
#
# This is required by Cumulus to access certain types of the
# runtime without clashing with the runtime api exported functions
# in WASM.
disable-runtime-api = []

# A feature that should be enabled when the runtime should be build for on-chain
# deployment. This will disable stuff that shouldn't be part of the on-chain wasm
# to make it smaller like logging for example.
on-chain-release-build = [
	"sp-api/disable-logging",
]

try-runtime = [
	"frame-try-runtime",
	"frame-executive/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-babe/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-bounties/try-runtime",
	"pallet-collective/try-runtime",
	"pallet-grandpa/try-runtime",
	"pallet-indices/try-runtime",
	"pallet-membership/try-runtime",
	"pallet-multisig/try-runtime",
	"pallet-proxy/try-runtime",
	"pallet-randomness-collective-flip/try-runtime",
	"pallet-recovery/try-runtime",
	"pallet-scheduler/try-runtime",
	"pallet-session/try-runtime",
	"serp-staking/try-runtime",
	"pallet-sudo/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-tips/try-runtime",
	"pallet-treasury/try-runtime",
	"pallet-utility/try-runtime",

	"orml-auction/try-runtime",
	"orml-authority/try-runtime",
	"orml-oracle/try-runtime",
	"orml-tokens/try-runtime",
	"orml-vesting/try-runtime",
	"orml-rewards/try-runtime",
	"orml-nft/try-runtime",

	"setheum-renvm-bridge/try-runtime",
	"setheum-dex/try-runtime",
	"setheum-incentives/try-runtime",
	"setheum-evm/try-runtime",
	"setheum-evm-accounts/try-runtime",
	"setheum-evm-bridge/try-runtime",
	"setheum-evm-manager/try-runtime",
	"setheum-prices/try-runtime",
	"serp-auction/try-runtime",
	"serp-treasury/try-runtime",
	"settmint-engine/try-runtime",
	"settmint-gateway/try-runtime",
	"settmint-manager/try-runtime",
	"setheum-currencies/try-runtime",
	"setheum-nft/try-runtime",
	"setheum-transaction-payment/try-runtime",
]