# Basic
hard_tabs = true
max_width = 120
use_small_heuristics = "Max"
comment_width = 100
wrap_comments = true
# Imports
imports_granularity = "Crate"
reorder_imports = true
# Consistency
newline_style = "Unix"
# Misc
chain_width = 100
spaces_around_ranges = false
binop_separator = "Back"
reorder_impl_items = false
match_arm_leading_pipes = "Preserve"
match_arm_blocks = false
match_block_trailing_comma = true
trailing_comma = "Vertical"
trailing_semicolon = false
use_field_init_shorthand = true
license_template_path = "HEADER-BUSL1.1"
