[package]
name = "settmint-gateway"
version = "0.8.0"
authors = ["Setheum Labs"]
edition = "2018"

[dependencies]
# external dependencies
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }

# Substrate dependencies
sp-runtime = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
frame-support = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
frame-system = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-std = { default-features = false, version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }

# orml dependencies
orml-tokens = { path = "../../../lib-openrml/tokens", default-features = false }

# local dependencies
settmint-engine = { package = "settmint-engine", path = "../settmint-engine", default-features = false }
settmint-manager= { package = "settmint-manager", path = "../settmint-manager", default-features = false }
support = { package = "setheum-support", path = "../../support", default-features = false }
primitives = { package = "setheum-primitives", path = "../../../primitives", default-features = false }

[dev-dependencies]
sp-core = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-io = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
pallet-balances = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
orml-currencies = { path = "../../../lib-openrml/currencies" }
orml-traits = { path = "../../../lib-openrml/traits" }
serp-treasury = { package = "serp-treasury", path = "../../serp/serp-treasury" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"sp-std/std",
	"orml-tokens/std",
	"settmint-manager/std",
	"settmint-engine/std",
	"support/std",
	"primitives/std",
]
try-runtime = ["frame-support/try-runtime"]
