[package]
name = "fetch-price"
authors = ["Setheum Labs"]
version = "0.1.0"
edition = "2018"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false }
frame-support = { version = "2.0.0", default-features = false}
frame-system = { version = "2.0.0", default-features = false }
serde = { version = "1.0.101", optional = true }
sp-core = { version = "2.0.0", default-features = false }
sc-keystore = { version = "2.0.0", optional = true }
sp-io = { version = "2.0.0", default-features = false }
sp-runtime = { version = "2.0.0", default-features = false }
sp-std = { version = "2.0.0", default-features = false }
lite-json = { version = "0.1", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"serde",
	"lite-json/std",
	"sp-core/std",
	"sp-io/std",
	"sc-keystore",
	"sp-runtime/std",
	"sp-std/std",
]